### ISSUE TITLE
fix: spell_check fails on warning

### ISSUE THREAD

**Issue by jinyus** [VeryGoodOpenSource/very_good_workflows#169]
**Description**
The "misspelt" words are in code blocks. This behavior is new because it code blocks didn't trigger errors in the past.

Here is the relevant run: https://github.com/jinyus/dart_beacon/actions/runs/7616833260/job/20744501121

**Comment by alestiago** [comment]
Hi @jinyus 👋 

Thank you for opening an issue! I'm not sure if I'm understanding correctly here.

You can add more words to the dictionary of words so that they are not considered "spelling mistakes". One way to do so is by having a `.github/cspell.json` file with the appropriate configuration.  Here is an example of the [`cspell` that Very Good Core is using](https://github.com/VeryGoodOpenSource/very_good_core/blob/main/brick/__brick__/%7B%7Bproject_name.snakeCase()%7D%7D/.github/cspell.json).

**Comment by jinyus** [comment]
Thanks, issue solved
